"""Configuración central de Sképsis Assistant."""
from pathlib import Path

APP_NAME = "Sképsis Assistant"
APP_VERSION = "0.8.2"
PAGE_TITLE = "Sképsis Assistant | Diagnóstico de proyectos"
MAX_MESSAGE_LENGTH = 500

RANDOM_SEED = 42
TRAIN_RATIO = 0.70
VALIDATION_RATIO = 0.15
TEST_RATIO = 0.15
MIN_EXAMPLES_PER_CLASS = 20
INTENT_CONFIDENCE_THRESHOLD = 0.30

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
SPLITS_DIR = DATA_DIR / "splits"
ASSETS_DIR = BASE_DIR / "assets"
ARTIFACTS_DIR = BASE_DIR / "artifacts"
REPORTS_DIR = BASE_DIR / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

KNOWLEDGE_BASE_PATH = DATA_DIR / "knowledge_base.json"
SERVICE_KNOWLEDGE_PATH = DATA_DIR / "service_knowledge_v2.json"
INTENTS_DATASET_PATH = DATA_DIR / "intents.csv"
TRAIN_SPLIT_PATH = SPLITS_DIR / "train.csv"
VALIDATION_SPLIT_PATH = SPLITS_DIR / "validation.csv"
TEST_SPLIT_PATH = SPLITS_DIR / "test.csv"

INTENT_MODEL_PATH = ARTIFACTS_DIR / "intent_baseline.joblib"
INTENT_MODEL_METADATA_PATH = ARTIFACTS_DIR / "intent_baseline_metadata.json"
SPRINT2_METRICS_PATH = REPORTS_DIR / "sprint2_metrics.json"

LOGO_LEFT_PATH = ASSETS_DIR / "skepsis-apps-logo.PNG"
LOGO_RIGHT_PATH = ASSETS_DIR / "Logo_Skepsis-Apps_Simbolo.PNG"
# Alias conservado por compatibilidad con componentes anteriores.
LOGO_PATH = LOGO_LEFT_PATH
COMPANY_SITE = "https://skepsis-apps.github.io/landing_page/"


# Sprint 3 — comparación recurrente
RECURRENT_ARTIFACTS_DIR = ARTIFACTS_DIR / "recurrent"
RECURRENT_REPORTS_DIR = REPORTS_DIR / "sprint3"
RECURRENT_FIGURES_DIR = RECURRENT_REPORTS_DIR / "figures"
RECURRENT_SELECTED_METADATA_PATH = RECURRENT_ARTIFACTS_DIR / "selected_model.json"
RECURRENT_SELECTED_WEIGHTS_PATH = RECURRENT_ARTIFACTS_DIR / "selected_model.pt"
RECURRENT_VOCAB_PATH = RECURRENT_ARTIFACTS_DIR / "vocab.json"
RECURRENT_LABELS_PATH = RECURRENT_ARTIFACTS_DIR / "labels.json"

RECURRENT_EMBEDDING_DIM = 48
RECURRENT_HIDDEN_DIM = 48
RECURRENT_NUM_LAYERS = 1
RECURRENT_DROPOUT = 0.15
RECURRENT_BATCH_SIZE = 32
RECURRENT_MAX_EPOCHS = 35
RECURRENT_PATIENCE = 6
RECURRENT_LEARNING_RATE = 0.003
RECURRENT_WEIGHT_DECAY = 0.0001
RECURRENT_GRAD_CLIP = 1.0
RECURRENT_SEEDS = (42, 123, 2026)
RECURRENT_MIN_TOKEN_FREQUENCY = 1
RECURRENT_MAX_SEQUENCE_LENGTH = 32
RECURRENT_CONFIDENCE_THRESHOLD = 0.30

# Checksums del split congelado al cerrar Sprint 2.
FROZEN_SPLIT_SHA256 = {
    "train.csv": "a0372838387b6caf2ca1a91cdd3dc7c27326e1adc9bbdc5ddfac5053ea08e409",
    "validation.csv": "3d005b7713b8cbc5c279947dd0a3d887a01d3fcb2ceaf0c1c3d25fb56ce6041c",
    "test.csv": "e08e81d5676e29c4cce5afec2bd22ed991443500e4cf2dcd44ab67e0474edf3a",
}


# Sprint 4 — embeddings y sentimiento
SENTIMENT_DATASET_PATH = DATA_DIR / "sentiment.csv"
SENTIMENT_EXTERNAL_EVAL_PATH = DATA_DIR / "sentiment_external_evaluation.csv"
SENTIMENT_SPLITS_DIR = DATA_DIR / "sentiment_splits"
SENTIMENT_TRAIN_PATH = SENTIMENT_SPLITS_DIR / "train.csv"
SENTIMENT_VALIDATION_PATH = SENTIMENT_SPLITS_DIR / "validation.csv"
SENTIMENT_TEST_PATH = SENTIMENT_SPLITS_DIR / "test.csv"

SPRINT4_ARTIFACTS_DIR = ARTIFACTS_DIR / "sprint4"
EMBEDDINGS_ARTIFACTS_DIR = SPRINT4_ARTIFACTS_DIR / "embeddings"
SENTIMENT_ARTIFACTS_DIR = SPRINT4_ARTIFACTS_DIR / "sentiment"
WORD2VEC_PATH = EMBEDDINGS_ARTIFACTS_DIR / "word2vec.kv"
GLOVE_WEIGHTS_PATH = EMBEDDINGS_ARTIFACTS_DIR / "glove.pt"
GLOVE_VOCAB_PATH = EMBEDDINGS_ARTIFACTS_DIR / "glove_vocab.json"
EMBEDDING_METADATA_PATH = EMBEDDINGS_ARTIFACTS_DIR / "metadata.json"
SENTIMENT_MODEL_PATH = SENTIMENT_ARTIFACTS_DIR / "sentiment_model.joblib"
SENTIMENT_METADATA_PATH = SENTIMENT_ARTIFACTS_DIR / "sentiment_metadata.json"

SPRINT4_REPORTS_DIR = REPORTS_DIR / "sprint4"
SPRINT4_FIGURES_DIR = SPRINT4_REPORTS_DIR / "figures"
SPRINT4_METRICS_PATH = SPRINT4_REPORTS_DIR / "sprint4_metrics.json"

EMBEDDING_DIM = 50
EMBEDDING_WINDOW = 4
WORD2VEC_EPOCHS = 100
GLOVE_EPOCHS = 120
GLOVE_X_MAX = 10.0
GLOVE_ALPHA = 0.75
GLOVE_LEARNING_RATE = 0.05
SENTIMENT_RANDOM_SEED = 42
SENTIMENT_VALIDATION_RATIO = 0.15
SENTIMENT_TEST_RATIO = 0.15
SENTIMENT_CONFIDENCE_THRESHOLD = 0.45


# Sprint 5 — generación controlada y neuronal experimental
SPRINT5_ARTIFACTS_DIR = ARTIFACTS_DIR / "sprint5"
GENERATION_ARTIFACTS_DIR = SPRINT5_ARTIFACTS_DIR / "generation"
SPRINT5_REPORTS_DIR = REPORTS_DIR / "sprint5"
SPRINT5_FIGURES_DIR = SPRINT5_REPORTS_DIR / "figures"

GENERATION_CORPUS_PATH = DATA_DIR / "generation_corpus.txt"
GENERATION_TRAIN_PATH = DATA_DIR / "generation_train.txt"
GENERATION_VALIDATION_PATH = DATA_DIR / "generation_validation.txt"
GENERATION_TEST_PATH = DATA_DIR / "generation_test.txt"

GENERATION_VOCAB_PATH = GENERATION_ARTIFACTS_DIR / "vocab.json"
GENERATION_LSTM_PATH = GENERATION_ARTIFACTS_DIR / "lstm.pt"
GENERATION_GRU_PATH = GENERATION_ARTIFACTS_DIR / "gru.pt"
GENERATION_LSTM_METADATA_PATH = GENERATION_ARTIFACTS_DIR / "lstm_metadata.json"
GENERATION_GRU_METADATA_PATH = GENERATION_ARTIFACTS_DIR / "gru_metadata.json"
GENERATION_SELECTED_WEIGHTS_PATH = GENERATION_ARTIFACTS_DIR / "selected_model.pt"
GENERATION_SELECTED_METADATA_PATH = GENERATION_ARTIFACTS_DIR / "selected_model.json"
GENERATION_METRICS_PATH = SPRINT5_REPORTS_DIR / "generation_metrics.json"

GENERATION_RANDOM_SEED = 42
GENERATION_EMBEDDING_DIM = 64
GENERATION_HIDDEN_DIM = 96
GENERATION_NUM_LAYERS = 1
GENERATION_DROPOUT = 0.10
GENERATION_BATCH_SIZE = 16
GENERATION_MAX_EPOCHS = 45
GENERATION_PATIENCE = 7
GENERATION_LEARNING_RATE = 0.003
GENERATION_WEIGHT_DECAY = 0.0001
GENERATION_GRAD_CLIP = 1.0
GENERATION_MAX_SEQUENCE_LENGTH = 40
GENERATION_MAX_NEW_TOKENS = 28


# Sprint 6 — Hugging Face local
SPRINT6_ARTIFACTS_DIR = ARTIFACTS_DIR / "sprint6"
HF_ARTIFACTS_DIR = SPRINT6_ARTIFACTS_DIR / "huggingface"
HF_MODEL_DIR = HF_ARTIFACTS_DIR / "flan-t5-small"
HF_MODEL_METADATA_PATH = HF_ARTIFACTS_DIR / "model_metadata.json"

SPRINT6_REPORTS_DIR = REPORTS_DIR / "sprint6"
SPRINT6_METRICS_PATH = SPRINT6_REPORTS_DIR / "hf_local_metrics.json"

HF_MODEL_ID = "google/flan-t5-small"
HF_MODEL_LICENSE = "apache-2.0"
HF_MODEL_TASK = "text2text-generation"
HF_MAX_INPUT_TOKENS = 384
HF_MAX_NEW_TOKENS = 80
HF_NUM_BEAMS = 2
HF_TEMPERATURE = 1.0
HF_DO_SAMPLE = False
HF_LOCAL_ONLY_IN_APP = True

HF_CONTEXT_MAX_CHARS = 2500
HF_QUESTION_MAX_CHARS = 500


# Sprint 7 — robustez, recursos y despliegue
DEPLOYMENT_PROFILE = "local"
CLOUD_PROVIDER = "Streamlit Community Cloud"
CLOUD_ENTRYPOINT = "deployment/streamlit/cloud_app.py"
CLOUD_PYTHON_VERSION = "3.11"
RESOURCE_REPORT_PATH = REPORTS_DIR / "sprint7" / "resource_profile.json"
ROBUSTNESS_REPORT_PATH = REPORTS_DIR / "sprint7" / "robustness_report.json"
RELEASE_REPORT_PATH = REPORTS_DIR / "sprint7" / "release_readiness.json"

MAX_SESSION_MESSAGES = 40
MAX_HISTORY_TURNS = 10
MAX_CLOUD_MESSAGE_LENGTH = 500


# Sprint 8 — atención ampliada por facetas de servicio
SPRINT8_REPORTS_DIR = REPORTS_DIR / "sprint8"
SPRINT8_SERVICE_REPORT_PATH = SPRINT8_REPORTS_DIR / "service_facets_check.json"
SPRINT8_RELEASE_REPORT_PATH = SPRINT8_REPORTS_DIR / "release_readiness.json"
